language: generic
sudo: false

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - make install-dependencies

env:
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis

script:
  - make check
